dist: trusty
sudo: required
language:
  - cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang
      - libX11-dev
script:
  # Link gcc-6 and g++-6 to their standard commands
  - ln -s /usr/bin/gcc-6 /usr/local/bin/clang
  - ln -s /usr/bin/g++-6 /usr/local/bin/clang++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/clang
  - export CXX=/usr/bin/clang++
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - sh clang_build_linux.sh Debug
